ini:
  server-ip: localhost
  poem-path: "assets/poem.csv"

spring:
  redis:
    host: ${ini.server-ip}
    port: 6379
#    password: redispwd123
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 50000
        max-active: 8

dubbo:
  application:
    name: dubbo-consumer-interface
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${ini.server-ip}:8848

