server:
  servlet:
    context-path: /api2
  port: 8123

spring:
  redis:
    host: localhost
    port: 6379
#    password: redispwd123
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: 50000
        max-active: 8

dubbo:
  application:
    name: dubbo-consumer-interface
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848

ini:
  poem-path: "assets/poem.csv"